---
title: "Pulling"
output: html_document
---

```{r}
library(tidyverse)
library(lubridate)
library(sf)
library(leaflet)
```

```{r}
if (is.null(p)) {
        neib_counts
      } else {
        
        res <- try(filter(neib_counts, name == p$id),silent = TRUE)
        
        if (class(res) == 'try-error') {
          
          neib_counts
          
        } else {
          
          neib_counts %>% 
            filter(name == p$id)
          
        }  
      }


if (is.null(p)) {
        
        districts_counts
        
      } else {
        
        res <- try(filter(districts_counts, supervisor == p$id), silent = TRUE)
        
        if (class(res) == 'try-error') {
          
          districts_counts
          
        } else {
          
          districts_counts %>% 
            filter(supervisor == p$id)
          
        }
      }
```


## testing bikeshare data and general outline of sf map data

```{r}
t <- read_csv("https://raw.githubusercontent.com/joshyam-k/schPull/master/data-folder/lime.csv")

t <- t %>% 
  mutate(last_updated = with_tz(last_updated, "America/Los_Angeles"))

#map <- st_read("/Users/joshuayamamoto/Downloads/SF Shoreline and Islands/geo_export_f07717d3-0581-4d32-ae60-c9b2f961271a.shp")

map <- st_crop(map, xmin = -122.54, xmax = -122.35, ymin = 37.7, ymax = 37.83)


```


# time pull function

```{r}
data_full <- t %>% 
  separate(
    last_updated,
    into = c("for_slider", "extra"),
    remove = F, sep = ":"
    ) %>% 
  mutate(full_date = ymd_h(for_slider)) %>% 
  mutate(
    hr = str_sub(full_date, -2),
    hr = as.numeric(hr)
    ) %>% 
  mutate(full_date = with_tz(full_date, "America/Los_Angeles")) %>% 
  mutate(pm_am = case_when(
    hr >= 12 & hr < 24 ~ "PM",
    T ~ "AM"
  )) 



test <- function(sf_obj) {
  
  counted <- data.frame()
  
  unique_dates <- data_full %>% 
    distinct(full_date)
  
  for (i in 1:nrow(unique_dates)) {
    
    filt <- data_full %>% 
      filter(full_date == unique_dates$full_date[[i]])
    
    coords <- filt %>% 
      select(lon, lat) %>% 
      st_as_sf(coords = c(1,2))
  
    coords_new <- coords %>% 
      st_set_crs(st_crs(sf_obj))
    
    sf_obj$n <- lengths(st_intersects(sf_obj$geometry, coords_new))
  
    sf_obj$datt <- unique_dates$full_date[[i]]
  
    counted <- rbind(counted, sf_obj)
    
    
  }
  
  counted %>% 
    as_tibble() %>% 
    select(-geometry)
  
}

t <- test(districts)


t %>% 
  filter(supdistpad == '01') %>% 
  ggplot(aes(x = datt, y = n)) +
  geom_line() +
  ylim(c(0,75))


# this should work
dd %>% 
  as_tibble() %>% 
  select(-link, -geometry) %>% 
  group_by(name) %>% 
  summarise(smallest = min(n), biggest = max(n)) %>% 
  ungroup() %>% 
  mutate(mid = (smallest + biggest)/2) %>% 
  mutate(name = fct_reorder(name, mid)) %>% 
  ggplot(aes(x = name, ymin = smallest, ymax = biggest)) +
  geom_linerange() +
  coord_flip()


```

## San Francisco neighborhoods

```{r}

# dealing with neighborhoods

neibs <- st_read("/Users/joshuayamamoto/Downloads/SF Find Neighborhoods/geo_export_9c547e56-21de-452a-96e8-e273dc0528f1.shp")

coords <- t %>% 
  select(lon, lat, ) %>%
  st_as_sf(coords = c(1,2))

coords_new <- coords %>% st_set_crs(st_crs(neibs))


neibs$n <- lengths(st_intersects(neibs$geometry, coords_new))

lls <- st_intersects(neibs$geometry, coords_new)

neibs %>% 
  ggplot() +
  geom_sf() +
  geom_sf(data = coords_new)

neibs %>% 
leaflet(options = leafletOptions(minZoom = 11, maxZoom = 14)) %>% 
  addProviderTiles(providers$MtbMap,
                   options = providerTileOptions(opacity = 0.15)) %>%
  addPolylines(color = "red", weight = 4) %>% 
  addProviderTiles(providers$Stamen.TonerLines,
                   options = providerTileOptions(opacity = 0.85)) %>% 
  addProviderTiles(providers$Esri.NatGeoWorldMap) %>% 
  addCircleMarkers(lng = ~lon, lat = ~lat,
                     data = , radius = 1)
```

using leaflet

```{r}
pal <- colorNumeric(palette = "Oranges", domain = neibs$n)
labl <- paste0(neibs$name, "<br>", "scooters: ", neibs$n)

neibs %>% 
leaflet(options = leafletOptions(minZoom = 11, maxZoom = 14)) %>% 
  addProviderTiles(providers$MtbMap,
                   options = providerTileOptions(opacity = 0.35)) %>%
  addProviderTiles(providers$Stamen.TonerLines,
                   options = providerTileOptions(opacity = 0.35)) %>% 
  addPolygons(color = ~pal(n), fillOpacity = 1.0, popup = labl) %>% 
  addPolylines(color = "black", weight = 1.5) %>% 
  addLegend("bottomright", pal = pal, 
            values = ~n, title = "Number of scooters",
            opacity = 1)
```


## San francisco districts

```{r}
districts <- st_read("shiny_app/sf_districts.shp")

districts %>% 
  ggplot() +
  geom_sf()

coords <- t %>% 
  select(lon, lat) %>%
  st_as_sf(coords = c(1,2))

coords_new <- coords %>% 
  st_set_crs(st_crs(districts))

districts$n <- lengths(st_intersects(districts$geometry, coords_new))

pal <- colorNumeric(palette = "Oranges", domain = districts$n)
labl <- paste0("District ", districts$supervisor, "<br>", "scooters: ", districts$n)

districts %>% 
leaflet(options = leafletOptions(minZoom = 11, maxZoom = 14)) %>% 
  addProviderTiles(providers$MtbMap,
                   options = providerTileOptions(opacity = 0.35)) %>%
  addPolygons(color = ~pal(n), fillOpacity = 1.0, popup = labl) %>% 
  addPolylines(color = "black", weight = 1.5) %>% 
  addProviderTiles(providers$Stamen.TonerLines,
                   options = providerTileOptions(opacity = 0.35)) %>% 
  addLegend("bottomright", pal = pal, 
            values = ~n, title = "Number of scooters",
            opacity = 1)

districts %>% 
  filter(supervisor == 4) %>% 
leaflet(options = leafletOptions(minZoom = 11, maxZoom = 14)) %>% 
  addProviderTiles(providers$MtbMap,
                   options = providerTileOptions(opacity = 0.15)) %>%
  addPolylines(color = "red", weight = 4) %>% 
  addProviderTiles(providers$Stamen.TonerLines,
                   options = providerTileOptions(opacity = 0.85)) %>% 
  addProviderTiles(providers$Esri.NatGeoWorldMap) %>% 
  addCircleMarkers(lng = ~lon, lat = ~lat,
                     data = test, radius = 1)

districts_test <- districts %>% 
  mutate(id = row_number())



indices_t <- st_intersects(districts$geometry, coords_new)

districts[districts$supervisor == 10, ] %>% 
  View()

test <- t[c(indices_t[[7]]), ]

```


## leaflet plot testing

```{r}
leaflet(options = leafletOptions(minZoom = 11, maxZoom = 14)) %>% 
  addProviderTiles(providers$MtbMap,
                   options = providerTileOptions(opacity = 0.35)) %>%
  addProviderTiles(providers$Stamen.TonerLines,
                   options = providerTileOptions(opacity = 0.35)) %>% 
  addProviderTiles(providers$Stamen.TonerLabels) %>% 
  addCircleMarkers(lng = ~lon, lat = ~lat,
                     data = t, radius = 1) %>% 
 
```

## how to add or subtract time

This will be used to help figure out my input sliders

```{r}
max <- max(t$last_updated)
min <- min(t$last_updated)
max <- with_tz(max, "America/Los_Angeles")

new_min <- max
min <- with_tz(min, "America/Los_Angeles")


week(max) <- week(max) - 2

```


