---
title: "Pulling"
output: html_document
---

```{r}
library(tidyverse)
library(lubridate)
library(sf)
library(leaflet)
```

```{r}

```


## testing bikeshare data and general outline of sf map data

```{r}
t <- read_csv("https://raw.githubusercontent.com/joshyam-k/schPull/master/data-folder/lime.csv")

t <- t %>% 
  mutate(last_updated = with_tz(last_updated, "America/Los_Angeles"))

map <- st_read("/Users/joshuayamamoto/Downloads/SF Shoreline and Islands/geo_export_f07717d3-0581-4d32-ae60-c9b2f961271a.shp")

map <- st_crop(map, xmin = -122.54, xmax = -122.35, ymin = 37.7, ymax = 37.83)


```

Want to be able to look at varying levels of aggregation

## San francisco districts

```{r}
districts <- st_read("shiny_app/sf_districts.shp")

districts %>% 
  ggplot() +
  geom_sf()

coords <- t %>% 
  select(lon, lat) %>%
  st_as_sf(coords = c(1,2))

coords_new <- coords %>% 
  st_set_crs(st_crs(districts))

districts$n <- lengths(st_intersects(districts$geometry, coords_new))

pal <- colorNumeric(palette = "Oranges", domain = districts$n)
labl <- paste0("District ", districts$supervisor, "<br>", "scooters: ", districts$n)

districts %>% 
leaflet(options = leafletOptions(minZoom = 11, maxZoom = 14)) %>% 
  addProviderTiles(providers$MtbMap,
                   options = providerTileOptions(opacity = 0.35)) %>%
  addProviderTiles(providers$Stamen.TonerLines,
                   options = providerTileOptions(opacity = 0.35)) %>% 
  addPolygons(color = ~pal(n), fillOpacity = 1.0, popup = labl) %>% 
  addPolylines(color = "black", weight = 1.5) %>% 
  addLegend("bottomright", pal = pal, 
            values = ~n, title = "Number of scooters",
            opacity = 1)



```

# old coords code
```{r}
coords <- data_full %>% 
  select(lon, lat) %>%
  st_as_sf(coords = c(1,2))

coords_new <- coords %>% 
  st_set_crs(st_crs(neibs))

neibs$n <- lengths(st_intersects(neibs$geometry, coords_new))

districts$n <- lengths(st_intersects(districts$geometry, coords_new))
```


```{r}

d <- data.frame()

time_counter <- function(df, level){
  #input is our full df
  
  for (i in df$last_updated) {
    
    new_l <- level
    
    filt_df <- df %>% 
      filter(last_updated == i)
      
    coords <-  filt_df %>% 
      select(lon, lat) %>%
      st_as_sf(coords = c(1,2))
    
    coords_new <- coords %>% 
      st_set_crs(st_crs(neibs))
    
    #new_l$n <- lengths(st_intersection(neibs$geometry, coords_new))
    
    #new_l$dattim <- i
    
    #d <- rbind(d, new_l)
    
  }
  d
  
}

time_counter(t, districts)
```

## San Francisco neighborhoods

```{r}

# dealing with neighborhoods

neibs <- st_read("/Users/joshuayamamoto/Downloads/SF Find Neighborhoods/geo_export_9c547e56-21de-452a-96e8-e273dc0528f1.shp")

coords <- t %>% 
  select(lon, lat, ) %>%
  st_as_sf(coords = c(1,2))

coords_new <- coords %>% st_set_crs(st_crs(neibs))


neibs$n <- lengths(st_intersects(neibs$geometry, coords_new))

neibs %>% 
  ggplot() +
  geom_sf() +
  geom_sf(data = coords_new)
```

using leaflet

```{r}
pal <- colorNumeric(palette = "Oranges", domain = neibs$n)
labl <- paste0(neibs$name, "<br>", "scooters: ", neibs$n)

neibs %>% 
leaflet(options = leafletOptions(minZoom = 11, maxZoom = 14)) %>% 
  addProviderTiles(providers$MtbMap,
                   options = providerTileOptions(opacity = 0.35)) %>%
  addProviderTiles(providers$Stamen.TonerLines,
                   options = providerTileOptions(opacity = 0.35)) %>% 
  addPolygons(color = ~pal(n), fillOpacity = 1.0, popup = labl) %>% 
  addPolylines(color = "black", weight = 1.5) %>% 
  addLegend("bottomright", pal = pal, 
            values = ~n, title = "Number of scooters",
            opacity = 1)
```


## leaflet plot testing

```{r}
leaflet(options = leafletOptions(minZoom = 11, maxZoom = 14)) %>% 
  addProviderTiles(providers$MtbMap,
                   options = providerTileOptions(opacity = 0.35)) %>%
  addProviderTiles(providers$Stamen.TonerLines,
                   options = providerTileOptions(opacity = 0.35)) %>% 
  addProviderTiles(providers$Stamen.TonerLabels) %>% 
  addCircleMarkers(lng = ~lon, lat = ~lat,
                     data = t, radius = 1) %>% 
 
```

## how to add or subtract time

This will be used to help figure out my input sliders

```{r}
max <- max(t$last_updated)
min <- min(t$last_updated)
max <- with_tz(max, "America/Los_Angeles")

new_min <- max
min <- with_tz(min, "America/Los_Angeles")


week(max) <- week(max) - 2




```


